name: multiply-platform
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - gdal=2.4
  - libgdal
  - pyproj
  - pyyaml
  - numpy
  - scipy
  - setuptools
  - gcc=12.1.0
  - cxx-compiler
  - libgcc=5.2.0
  - lazrs-python
  - laspy
  - plyfile
  - types-pkg_resources
  - shapely
  - pyshp
  - pytest
  - flake8
  - pip
  - pip:
      - .

