name: multiply-platform-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.6*
  #
  # runtime dependencies
  #
  - astor = 0.8
  - beautifulsoup4 = 4.6.0
  - colorama = 0.4
  - gdal = 2.4
  - freetype = 2.10
  - h5py = 2.8.0
  - html5lib = 1.0.1
  - jupyter = 1.0
  - lightgbm = 2.1
  - lxml = 4.3.2
  - matplotlib = 2.2
  - netcdf4 = 1.5
  - numba = 0.46
  - numpy = 1.16
  - pandas = 0.22
  - psutil = 5.6
  - pyproj = 2.2
  - pyyaml = 3.12
  - recommonmark
  - requests = 2.18.4
  - scipy = 1.2.1
  - scikit-image = 0.15
  - scikit-learn = 0.20
  - setuptools = 40.8.0
  - shapely = 1.6.4
  - six = 1.12
  - tensorflow = 1.13
  - termcolor
  - typing
  - webencodings
  - xarray = 0.13.0
  # UI
  - ipywidgets = 7.4.2
  - jupyterlab = 0.35.4
  - tornado = 5.1.1
  - ipyleaflet = 0.10.4
  # PMonitor
  - inflection = 0.3.1
  # Docs
  - mock = 2.0.0
  - sphinx = 1.8.4
  - sphinxcontrib-bibtex = 0.4
    # Testing
  - pytest = 4.6
  - pytest-cov = 2.7
