name: multiply-platform
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - gdal=3.4
  - pyproj
  - pyyaml
  - numpy
  - scipy
  - setuptools
  - gcc=12.1.0
  - cxx-compiler
  - libgcc=5.2.0
  - lazrs-python
  - laspy
  - plyfile
  - shapely
  - pyshp
  - pytest
  - pip
  - pip:
      - .

