name: multiply-platform
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - gdal
  - pyproj
  - pyyaml
  - numpy
  - scipy
  - setuptools
  - shapely
  - pip
  - pip:
      - -r requirements.txt
      - .

