name: multiply-platform-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.6*
  #
  # runtime dependencies
  #
  - beautifulsoup4 = 4.6.0
  - shapely = 1.6.2
  - gdal = 2.2.4
  - numpy = 1.15
  - h5py = 2.7.1
  - html5lib = 1.0.1
  - pyyaml = 3.12
  - requests = 2.18.4
  - pytest =3.8.0
  - matplotlib >= 2.1.2
  - mock = 2.0.0
  - netcdf4 >= 1.4.0
  #- osr
  - pandas >= 0.22.0
  - scipy=1.0
  - scikit-learn
  - setuptools
  #- datetime
  #- pickle
  #- xml
