name: multiply-platform

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9
  #
  # runtime dependencies
  #
  - astor
  - beautifulsoup4
  - setuptools
#  - colorama
  - gdal
  - pdal
  - python-pdal
#  - geojson
#  - freetype
#  - h5py
#  - html5lib
#  - jupyter
#  - lightgbm
#  - lxml
#  - matplotlib
#  - netcdf4
#  - numba
  - numpy
#  - pandas
#  - psutil
  - pyproj
  - pyyaml
#  - recommonmark
#  - requests
  - scipy
#  - scikit-image
#  - scikit-learn
  - shapely
#  - six
#  - tensorflow
#  - termcolor
#  - typing
#  - webencodings
#  - xarray
#  # Server
#  - click
#  - inflection
#  # UI
#  - ipyleaflet
#  - ipywidgets
#  - jupyterlab
#  - nodejs
#  - tornado
#  # Docs
  - mock
#  - sphinx
#  - sphinxcontrib-bibtex
#    # Testing
  - pytest
  - pytest-cov
