channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6*
  - gdal>2.1
  - lightgbm
  - poppler<0.66
  - pip
  - pip:
    - sphinxcontrib-bibtex
    - sentinelhub
    - pyproj
    - netCDF4
    - shapely
    - scipy
    - python-dateutil
    - numpy==1.13.1
    - h5py==2.7.1
    - pandas==0.22.0
    - matplotlib==2.1.2
    - pytest==3.2.1
    - PyYAML==3.12
    - xarray


