channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6*
  - gdal>2.1
  - lightgbm
  - poppler<0.66
  - pip
  - pip:
    - sphinxcontrib-bibtex
    - sentinelhub
    - pyproj
    - netCDF4
    - shapely


