name: Python Package using micromamba

on: 
  push:
  schedule:
  - cron: '0 0 2 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!