name: Python Package using Conda

on: 
  push:
  schedule:
  - cron: '0 0 2 * *'

jobs:
  build:
    strategy:
      max-parallel: 5
      matrix:
        environment_file: [environment.yml]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file:  ${{ matrix.environment_file }}


      - name: Lint with flake8
        run: |
          micromamba install -c conda-forge flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          micromamba install -c conda-forge pytest
          pytest