name: Python Package using micromamba

on: 
  push:
  schedule:
  - cron: '0 0 2 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          cache-env: true


      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -c "flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics"
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
           python -c  "flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics"
      - name: Test with pytest
        run: |
           python -c "pytest"
        


